### ISSUE TITLE
package ‘Sxslt’ is not available (for R version 3.1.2)

### ISSUE THREAD

**Issue by suensummit** [beanumber/openWAR#23]
As title: package ‘Sxslt’ is not available (for R version 3.1.2)

- R version 3.1.2 (2014-10-31) -- "Pumpkin Helmet"
- RStudio Version 0.98.1091 
- Mac OS X Yosemite 10.10.1

Thanks!

**Comment by gjm112** [comment]
The 'Sxslt' package is not available on CRAN.  It's in the Omega Hat (http://www.omegahat.org/) repository.

**Comment by suensummit** [comment]
Sorry that I should paste the whole error messages here:

```
> install.packages("Sxslt", repos = "http://www.omegahat.org/R", type = "source")
trying URL 'http://www.omegahat.org/R/src/contrib/Sxslt_0.91-3.tar.gz'
Content type 'application/x-gzip' length 200341 bytes (195 Kb)
opened URL
==================================================
downloaded 195 Kb

* installing *source* package ‘Sxslt’ ...
R_ONLY = yes
checking for xslt-config... /usr/bin/xslt-config
configure: creating ./config.status
config.status: creating src/Makefile
config.status: creating cleanup
config.status: creating src/Makevars
** libs
clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -g -D_R_=1 -DUSE_R=1  -DXSL_IN_R_ONLY -DHAVE_R_EMBEDDED_H -I/Library/Frameworks/R.framework/Resources/include  -I/ -I/usr/include/libxml2  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include    -fPIC  -Wall -mtune=core2 -g -O2  -c Converters.c -o Converters.o
In file included from Converters.c:1:
./Converters.h:9:10: fatal error: 'libxml/tree.h' file not found
#include <libxml/tree.h>
         ^
1 error generated.
make: *** [Converters.o] Error 1
ERROR: compilation failed for package ‘Sxslt’
* removing ‘/Library/Frameworks/R.framework/Versions/3.1/Resources/library/Sxslt’
Warning in install.packages :
  installation of package ‘Sxslt’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/bg/n6sj167s5wgd441kqrdlx0qw0000gn/T/Rtmp2qNnMq/downloaded_packages’
> 
```

It sounds like my Mac was lack of the file "libxml/tree.h", but it doesn't work even after I ```brew install libxml2``` ...

**Comment by beanumber** [comment]
In Mavericks (OS X 10.9.5) I had this same problem. Doing this:
```
xcode-select --install
```
fixed it. 

Reference: http://stackoverflow.com/questions/19548011/cannot-install-lxml-on-mac-os-x-10-9

**Comment by suensummit** [comment]
It works out! Thanks!

**Comment by beanumber** [comment]
On Ubuntu 14.04.2 LTS, the fix for the same error is:

```
sudo apt-get install libxslt1-dev
```
You probably also need:

```
sudo apt-get install libxslt1.1 libxml2 libxml2-dev
```

**Comment by mjr2000** [comment]
Does anyone know what the problem is? I guess the website was taken down.

`> install.packages("Sxslt", repos = "http://www.omegahat.org/R", type = "source")
Warning in install.packages :
  cannot open URL 'http://www.omegahat.org/R/src/contrib/PACKAGES.rds': HTTP status was '404 Not Found'
Warning in install.packages :
  cannot open URL 'http://www.omegahat.org/R/src/contrib/PACKAGES.gz': HTTP status was '404 Not Found'
Warning in install.packages :
  cannot open URL 'http://www.omegahat.org/R/src/contrib/PACKAGES': HTTP status was '404 Not Found'
Warning in install.packages :
  unable to access index for repository http://www.omegahat.org/R/src/contrib:
  cannot open URL 'http://www.omegahat.org/R/src/contrib/PACKAGES'
Warning in install.packages :
  package ‘Sxslt’ is not available (for R version 3.4.0)`

**Comment by beanumber** [comment]
@mjr2000 this was discussed in the issues referenced above. Try;
```
devtools::install_github("cboettig/Sxslt")
```
or 
```
devtools::install_github("beanumber/Sxslt")
```
instead.

**Comment by mjr2000** [comment]
The second code worked! Thanks.
